name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to run this manually anytime
  schedule:
    - cron: "0 8 * * 6" # Runs automatically every Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }} # Matches your exact name
          leetcode-session: ${{ secrets.LEETCODE_SESSION }} # Matches your exact name
